import{a as S,S as $,i as f}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function g(t,r,n){try{return(await S.get("https://pixabay.com/api/",{params:{key:"51391148-cca0cd30758df7ebb9b563956",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:n,page:r}})).data}catch{return[]}}const M=document.querySelector(".form"),y=document.querySelector('input[name="search-text"]'),h=document.querySelector("#loader"),b=document.querySelector(".gallery"),d=document.querySelector(".load-more"),B=new $(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function L(t){const r=t.map(({webformatURL:n,largeImageURL:i,tags:e,likes:o,views:a,comments:q,downloads:v})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${i}">
        <img class="gallery-image" src="${n}" alt="${e}" />
      </a> 
      <ul class="gallery-item-prop">
        <li class="gallery-item-likes"><p><span>Likes</span><p>${o}</p></li>
        <li class="gallery-item-views"><p><span>Views</span><p>${a}</p></li>
        <li class="gallery-item-comments"><p><span>Comments</span><p>${q}</p></li>
        <li class="gallery-item-downloads"><p><span>Downloads</span><p>${v}</p></li>
      </ul>
    </li>
  `).join("");b.insertAdjacentHTML("beforeend",r),B.refresh()}function E(){b.innerHTML=""}function w(){h.style.display="inline-block"}function u(){h.style.display="none"}function I(){d.style.display="block"}function m(){d.style.display="none"}const p=15;m();let s=0,l="";M.addEventListener("submit",t=>{if(t.preventDefault(),l=y.value.trim(),s=1,!l){c("Поле пошуку не може бути порожнім");return}m(),E(),w(),g(l,s,p).then(r=>{u(),y.value="",Math.ceil(r.totalHits/p)>s&&I(),r.hits.length===0?c("Sorry, there are no images matching your search query. Please try again!"):L(r.hits)}).catch(()=>{u(),c("Щось пішло не так... Ми вже працюємо над цією проблемою.")})});d.addEventListener("click",()=>{m(),w(),s++,g(l,s,p).then(t=>{u(),L(t.hits),O(),Math.ceil(t.totalHits/p)>s?I():P("We're sorry, but you've reached the end of search results.")}).catch(()=>{u(),c("Щось пішло не так... Ми вже працюємо над цією проблемою.")})});function c(t){f.error({title:"Error",message:`${t}`,progressBar:!1,transitionIn:"fadeIn",position:"topRight",animateInside:!0})}function P(t){f.info({title:"End",message:`${t}`,progressBar:!1,transitionIn:"fadeIn",position:"topRight",animateInside:!0})}function O(){const r=document.querySelector(".gallery-item").getBoundingClientRect();setTimeout(()=>{window.scrollBy({top:r.height*2,behavior:"smooth"})},700)}
//# sourceMappingURL=index.js.map
